name: Publish package to GitHub Packages

on:
  push:
    tags:
      - "[0-9]+.[0-9]+.[0-9]+"
      - "[0-9]+.[0-9]+.[0-9]+-[0-9]+" # release candidate
  # release:
  #   types: [published]

jobs:
  check-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      # Setup .npmrc file to publish to GitHub Packages
      - name: get-npm-version
        id: package-version
        uses: martinbeentjes/npm-get-version-action@v1.3.1
        with:
          path: lib
      - name: Fail if different version
        if: ${{ steps.package-version.outputs.current-version != github.ref_name }}
        run: exit 1

  build:
    if: needs.check-version.outputs.status == 'success'
    defaults:
      run:
        working-directory: lib
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      # Setup .npmrc file to publish to GitHub Packages
      - name: get-npm-version
        id: package-version
        uses: martinbeentjes/npm-get-version-action@v1.3.1
        with:
          path: lib
      - uses: actions/setup-node@v4
        with:
          node-version: "20.x"
          registry-url: "https://npm.pkg.github.com"
          # Defaults to the user or organization that owns the workflow file
          scope: "@datavillage-me"
      - run: yarn install --frozen-lockfile
      # - uses: qoomon/actions--access-token@v3
      #   id: access-token
      #   with:
      #     permissions: |
      #       packages: write
      - run: yarn publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }} # token autogenerated by github
